### ISSUE TITLE
구조체 user->seat로 변경

### ISSUE THREAD

**Issue by Sunghaeun** [Sunghaeun/OSS_teamproject#14]
0,1,2번 유저에 자리를 지정하는 것이 아닌 바로 자리 지정해서 좌석을 결정할수있게함

**Comment by yohan-seo** [comment]
일단 user을 seat로 바꿨어!

**Comment by yohan-seo** [comment]
지금 seat.c에서 바꾸고 있는거 맞지?

**Comment by yohan-seo** [comment]
함수 정의하는 부분에서 user *u[]이런식으로 되어 있어서 seat *u[]로 바꿔놨고 u->seat부분을 모두 지워놨어!

**Comment by yohan-seo** [comment]
기각...
