### ISSUE TITLE
좌석 seat 관련

### ISSUE THREAD

**Issue by Sunghaeun** [Sunghaeun/OSS_teamproject#9]
우리가 배열로 해서 seat를 표시하려고 했잖아 근데 코드 짜다보니깐 이 방법보다 이 방법이 더 괜찮으거 같아서 확인하고 수정할 부분 코멘트 해주면 수정해볼께!

CRUD.h 에 있는 user 구조체에서 처음에는  int seat 를 0으로 해두고 좌석의 좌석의 번호를 저장해두기
그래서 나중에 ~번 좌석의 정보를 읽어올 때 user들의 seat값이 0이 되는 것을 찾도록 하려구해

아직 other부분을 다 못 짜서 혹시 이해 안되는 부분 있으면 알려줘

**Comment by yohan-seo** [comment]
완료
